### 简介				 				

Java程序中发现错误的理想时机是在编译阶段，也就是在你试图运行程序之前。然而，编译期间并不能找出所有的错误，余下的问题必须在运行期间解决。这就需要错误源能通过某种方式，把适当的信息报告给我们。异常则是 Java 中唯一官方的错误报告机制，运用好异常这个特性，我们才可能写出健壮可靠的程序，其效果是立竿见影的。 	 

### 异常是什么？

当程序运行发生错误时，Java通常会发出一个错误报告，这个报告上面写着详细的错误信息。这个报告就叫异常

Java异常：Java程序在运行时出现了问题，可能是我导致的，也可能是别人导致的，我对此感到意外。

**发生异常**

具体来讲，这个错误报告以对象的形式从发生错误的那行代码被抛出，同 Java 中其他对象的创建一样，将 使用 new 在堆上创建异常对象。然后，当前的执行路径(它不能继续下去了)被终止 ，异常处理机制接管程序，随后会有两种情况：

- 崩溃：如果我们的代码对其坐视不理，那么这个错误报告会在对应线程的运行栈空间里不断被抛下去，直至最后的mian方法的栈帧都被他搞坏了，线程就崩溃了。
- 处理：如果我们在代码中编写了异常处理程序，那么它就可以将程序从错误状态中恢复，以使程序能要么换一种方式运行，要么继续运行下去，这取决于我们编写的异常处理程序。

**异常类型**

即然异常是一种错误报告，那么异常的类型也就是可能发生错误的种类。Java中异常的数目在持续增加，第三方库里也有其自己的异常类型，罗列毫无意义，关键是理解异常的概念以及如何使用。

### 如何使用异常？

无论是主动还是被动，异常对象都是在堆上被创建出来，随后被throw给异常管理机制。

一是构造，而是throw：

所有标准的异常类都有两个构造器，

- 无参构造器，
- 字符串为参数的构造器，以便把相关信息放入异常对象

```groovy
public static void throwNPE(Object pointer){
    NullPointerException npe = new NullPointerException();
    if (pointer == null) {
        throw npe;
    } else {
        throw new NullPointerException("throw npe, although pointer is not null");
    }
}
```



下方显示了一个简单的嵌套调用。在最内层函数抛出了一个npe，然而当到达最外层的main函数才被处理。无论途径的方法调用如何。我们可以看出异常对象的类型通常与方法的返回类型完全无关，但从效果上看，抛出异常后，就像是从方法中返回了。但仅仅是效果上，因为返回的地点差异很大：方法返回值很快就会被上层方法处理，而异常很可能会在跨过层层的方法调用栈之后才被处理。

```groovy
public class UseException {
    public static void main(String[] args) {
        try {
            System.out.println(f());
        } catch (NullPointerException e) {
            System.out.println("NullPointerException happened");
        }
    }

    public static int f(){
        g();
        return 0;
    }

    public static void g(){
        throwNPE(null);
    }
}
```

对于不同类型的错误，我们要抛出相应的异常。错误信息可以借助异常对象（异常信息，异常的名字）来交给上一级 

**异常发生及捕获**

 					 				

要明白异常是如何被捕获的，必须首先理解监控区域(guarded region)的概念。它 是一段可能产生异常的代码，并且后面跟着处理这些异常的代码。 

这就是上面的try catch。

有了这种机制，可以把所有动作都放在 try 块里，然后只需在一个地方就可以捕获所有异常。这意 味着你的代码将更容易编写和阅读，因为代码的意图和错误检查不是混淆在一起的。 尤其是从java7开始，我们可以开始进行多重异常的捕获了，这可以让我们的异常处理程序更为简洁。

```groovy
public class MultiCatch {
    void process() { }
    public void x() throws Except1, Except2 {} 
    public void y() throws Except3, Except4 {} 
    public void f() {
        try { 
            x();
            y();
        } catch(Except1 | Except2 | Except3 | Except4 e) { 
            process();
        } 
    }
}
```



而我们进行参数校验虽然减小try 块的大小，但是我们要明确，try块变小了，并不意味着发生异常时处理得更快了，而是而是减少了发生异常的可能。

try catch的确会带来额外的性能开销，但这与try代码块的大小无关。因此既然选择了try catch编程时，最关键的是保证健壮性和可读性，即保证所有可能发生异常的地方被捕获，那些在发生异常后之后不会用到的变量就放在try块中就好了。







**异常处理**

e.printStackTrace() 将会打印 从方法调用出一直到异常抛出处的方法序列到系统错误流System.error中，人们都称之为堆栈信息。在详细一些说，这个方法会返回一个由栈轨迹中元素组成的数组，第一个元素表示调用序列中最后一个方法调用（抛出异常的方法），最后一个元素表示调用序列中第一个方法调用。

而直接使用e.toString() 只能显示出异常对象的信息。

比如：

但是请注意，在应用发布之后，发生异常时使用e.printStackTrace()只会在控制台打印对战信息，我们更希望能记录到日志文件当中，而且我们经常会使用Slf4j等日志工具，因此我们需要了解日志工具的使用方式。例如使用Slf4j的log：

```groovy
try {
    // 下标越界
    int[] array = new int[]{1, 2};
    System.out.println(array[2]);
} catch (Exception e) {
    log.error(e)
    log.error("IndexOutOffBound exception"+ e);// 唯一的参数被当作字符串
    log.error("IndexOutOffBound exception", e);// 第二个参数是Throwable类型
}

输出结果如下；
1、com.laone.类名 6 main - java.lang.ArrayIndexOutOfBoundsException：2
1、com.laone.类名 6 main - IndexOutOffBound exception java.lang.ArrayIndexOutOfBoundsException：2
1、com.laone.类名 6 main - IndexOutOffBound exception java.lang.ArrayIndexOutOfBoundsException：2
    at com.laone.......堆栈信息...
    at com.laone.......堆栈信息...
```

因此，要打印完整的堆栈错误信息请务必使用logger.error(“错误”,e)

将异常重新抛出也是一种处理方法，大概意思是：该方法处理不了这个异常，只好抛给该方法的上级。有一点需要明确，如果直接将异常抛出，异常对象中的堆栈信息仍然是全链路的堆栈信息，而如果在某一点是用了e.fillStackTrace()，则会丢弃之前的堆栈信息，即调用 fillInStackTrace() 的那一行变成了异常的新发生地。

异常链

在对捕获到的异常进行处理的时候，我们可能想再度抛出其他异常，并且保留原来发生异常的堆栈信息。这需要我们使用initCause方法，够将异常的信息链接在一起。下面是一个例子。ExceptionList



 ```java
 // 支付异常类
 class PaymentException extends Exception {
     public PaymentException(String message) {
         super(message);
     }
 }
 
 // 余额不足异常类，继承自支付异常
 class InsufficientBalanceException extends PaymentException {
     public InsufficientBalanceException(String message) {
         super(message);
     }
 }
 ```









 	 	 		

 			

 				

**自定义异常**



我们不必拘泥于 Java 已有的异常类型。Java 异常体系不可能预见你将报告的所有错误， 所以你可以创建自己的异常类，来表示你的程序中可能遇到的问题。要自己定义异常类，必须从已有的异常类继承，最好是选择意思相近的异常类继承 





**异常限制**



**当覆盖重写基类的方法时，异常说明也必须遵守一定规则，使得同基类一起工作的代码，依然可以和子类一起正常工作。否则，在使用基类的时候就不能判断是否使用了正确的异常。**



Dog类继承Pet的同时还实现了Animal接口，因此在对feed(）方法进行重写的时候 必须要保证 抛出的异常同时是Pet中所抛出的FeedException，Animal所抛出的DoException 二者的子类或同级。

XXXX 处什么都不填是可以的，填写为FeedException，也是可以的，但是不可以填写DoExcpetion。

```groovy
// 两个异常类存在继承关系时
class FeedException extends DoException{}
class DoException extends Exception{}


class Dog extends Pet implements Animal {
    
    @Override
    public void feed() throws XXXX{
        // XXXX 可以写什么呢？？
    }
}

abstract class Pet {
    public abstract void feed() throws FeedException;
}

interface Animal {
    void feed() throws DoException;
}
```

**我们所做的一切，都是为了让下面这段代码依然可以正确运行，即保证在执行feed()所抛出的异常可以被捕捉。**

```groovy
public class ExtendException {
    public static void main(String[] args) {
        // 宠物狗
        Pet dog1 = new Dog();
        try {
            dog1.feed();
        } catch (FeedException e) {
            e.printStackTrace();
        }
        
        // 动物狗
        Animal dog2 = new Dog();
        try {
            dog2.feed();
        } catch (DoException e) {
            e.printStackTrace();
        }
    }
}
```





```groovy
// 两个异常类不存在继承关系时
class FeedException extends DoException{}
class DoException extends Exception{}

class Dog extends Pet implements Animal {

    @Override
    public void feed() throws XXXX{
    	// XXXX可以填什么才能让上端代码通过编译呢？
    }

    public void sleep() throws XXXX{
        // XXXX 可以填什么呢？
    }
}

abstract class Pet {
    public abstract void feed() throws FeedException;
}

interface Animal {
    void feed() throws DoException;
}
```

结论：对于父子类间继承的方法，子类方法抛出的异常 一定要是父类方法抛出的异常的子类

上面的例子也提醒了我们，父类方法中声明的异常可以不必出现在子类方法的生命当中。

异常限制的性质可以总结为，随着继承，子类方法中抛出的异常范围越来越小了，甚至消失。



**Java编译器对异常的这种限制的目的是：要求程序员编写更为健壮的异常处理代码。**

值得注意的：虽然在继承的时候编译器会对方法的异常声明作出种种限制，就像对方法的返回值，入参类型进行的检查一样。但是异常说明本身并不属于类型的一部分。因此不能基于异常说明来重载方法。



**构造器异常**



Q：如果异常发生了，所有东西都能被正确的清理吗？

A：大多数情况下都是可以的，但是涉及类似构造器的操作步骤时，问题出现了。

你或许会认为在finally中编写清理程序就可以解决一切问题，但是事实上并没有如此简单。请看下面的这个例子：

```groovy
public class ConstructException {
    public static void main(String[] args) {
        // 对于在构造阶段可能会抛出异常，并且要求清理的类，最安全的使用方式是使用嵌套的 try 子句:
        String fileName = "happy new year";
        try {
            InputFile inputFile = new InputFile(fileName);
            int cnt = 10;
            try {
                while (cnt-- > 0) {
                    String line = inputFile.getLine();
                }
            } catch (Exception e) {
                System.out.println("get line failed");
            } finally {
                inputFile.dispose();
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

class InputFile {
    private BufferedReader in;

    public InputFile(String fname) throws Exception {
        try {
            in = new BufferedReader(new FileReader(fname));
        } catch (FileNotFoundException e) {
            System.out.println("Could not open " + fname);
            throw e;
        } catch (Exception e) {
            try {
                in.close();
            } catch (IOException e2) {
                System.out.println("in.close() unsuccessful");
            }
            throw e;
        }
    }

    public String getLine() {
        String s;
        try {
            s = in.readLine();
        } catch (IOException e) {
            throw new RuntimeException("readLine() failed");
        }
        return s;
    }

    public void dispose() {
        try {
            in.close();
            System.out.println("dispose() successful");
        } catch (IOException e2) {
            throw new RuntimeException("in.close() failed");
        }
    }
}
```



事实上，这种清理习惯同样适用于非构造方法，其基本规则通过下列的练习便可掌握：

1、创建一个需要清理的对象

2、创建两个需要清理的对象，分两种情况



虽然上面的例子有些混乱，我们平时大多数时间也不会遇到，但这基于我们在设计的时候就避免出现这种麻烦的情况，因此你仍然必须要理解它。

比如对上面的程序利用Stream进行简化，因为在 java8 中，流不能被重用，一旦它被启动，结束时流将被自动关闭。

```groovy
class InputFile2 {
    private String fileName;
    public InputFile2(String fileName) {
        this.fileName = fileName;
    }

    public Stream<String> getLines() throws IOException {
        return Files.lines( Paths.get(fileName));
    }
}
```



**try-with-Resources**

**尽管我们充分了设计，依然还是有些不可避免的麻烦情况，比如**

```groovy
public static void main(String[] args) {
    File file = new File("123");
    FileInputStream in = null;
    try {
        in = new FileInputStream(file);
        int read = in.read();
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        if (in != null) {
            try {
                in.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

幸运的是，Java7之后引入了try-with-resources，try的后面开始可以跟着（）,括号里面定义的部分称为资源规范头（他们必须实现AutoCloseable接口，而这个接口只有一个close方法），无论你如何退出try块，资源头中的资源都会被自动关闭，而不用你手动执行哪些麻烦的操作。这是一项重要的改进

```groovy
public static void main(String[] args) {
    File file = new File("123");
    try(
            FileInputStream input = new FileInputStream(file);
    ) {
        int read = input.read();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

注意：这里的资源头中可以包含多个定义，并且动过分号进行分割，每个对象都会在退出try块时调用其close()方法，进行安全的关闭。并且遵循着顺序：先创建的 后关闭。原因是：后创建的可能依赖于先创建的。



 	 	 		

**异常声明原则**

java鼓励人们将可能发生的异常告知给方法调用者，声明的方法如下。



这是一种礼貌且优雅的方式，由此以来，方法调用者无论如何都要编写出能够处理这种类型异常的方法，即便他选择继续向上抛出，那也是算是我们告知了他。

​	

不过还是有个能 “作弊” 的地方:可以声明方法将抛出异常，实际上却不抛出。编译器相信了这个声明，并强制此方法的用户像真的抛出异常那样使用这个方法。 

这是编译器强制检查的，因此也叫做受检查的异常。



受检异常是Java语言所独有的，它强制要求方法的调用者做好发生异常的准备，即无论有没有异常发生，你都应该编写相应的异常处理程序。这是你想要调用我必须遵守的规范。定下这个规范的好处就在于，我们有了一个统一的，实用一场来报告错误的模型。

但同时这方面的设计也存在一些负面观点，例如其可能会引发糟糕的异常处理---吞食即有害 harmful if swallowd ，我们允许通过一个处理程序去处理多个出错点，异常处理还使得错误处理代码的数量趋于减少。但是在这个过程中，我们将一些异常情况忽略了，这回导致异常处理程序忽略了一些重要信息。令我们难以排查  				



异常处理的一个重要原则是 “只有在你知道如何处理的情况下才捕获异常”。



### 本章总结

简单来说，异常被设计的目标就是把处理错误的代码同错误发生的地点相分离。这使你 能在一段代码中专注于要完成的事情，至于如何处理错误，则放在另一段代码中完成。 这样一来，主要代码就不会与错误处理逻辑混在一起，也更容易理解和维护。 			

 					 				

无论 是否正确，我一直相信 “报告” 功能是异常的精髓所在. Java 坚定地强调将所有的错误 都以异常形式报告的这一事实，正是它远远超过如 C++ 这类语言的长处之一，因为在 C++ 这类语言中，需要以大量不同的方式来

报告错误，或者根本就没有提供错误报告 功能。一致的错误报告系统意味着，你再也不必对所写的每一段代码，都质问自己 “错 误是否正在成为漏网之鱼?”(只要你没有 “吞咽” 异常)。 



异常是 Java 程序设计不可分割的一部分，如果不了解如何使用它们，那你只能完 成很有限的工作。 而	利用好Java的异常（try,catch,finally），可以让我们的程序更加健壮，异常的信息也让我们能够发现编程错误或者业务问题，从而不断优化我们的程序。	



应该在下列情况下使用异常:

1. 尽可能使用 try-with-resource。
2. 在恰当的级别处理问题。(在知道该如何处理的情况下才捕获异常。)
3. 解决问题并且重新调用产生异常的方法。
4. 进行少许修补，然后绕过异常发生的地方继续执行。
5. 用别的数据进行计算，以代替方法预计会返回的值。
6. 把当前运行环境下能做的事情尽量做完，然后把相同的异常重抛到更高层。
7. 把当前运行环境下能做的事情尽量做完，然后把不同的异常抛到更高层。
8. 让类库和程序更安全。(这既是在为调试做短期投资，也是在为程序的健壮性做长
   期投资。)

 				**思考：实际上Java的还有一种错误叫做Error，我们如何处理他们呢？**

他们都是java程序发生了错误， Exception是代码逻辑导致的，经过一些处理往往可以恢复到正常运行的状态。而error则表示JVM系统级错误，它是虚拟机抛出的，一旦发生就很难恢复了，此时也的确应该停下这台机器好好修复一下。

- 假设进行网络连接操作的时候，IOException 发生了，可能是网络中断，我可以再尝试几次。
- 假设OutOfMemoryError发生了，就算被捕捉了，可以有什么手段让程序正常运行下去吗？ 
- 假设ExceptionInInitializerError发生了，类无法被正常初始化，这个也不是通过简单处理就可以恢复的

```java
public class Example {
    // 声明受检异常
    public static void main(String[] args) {
        try {
            // 调用抛出异常的方法
            throwCheckedException();
        } catch (CustomCheckedException e) {
            System.out.println("捕获到受检异常: " + e.getMessage());
        }
    }

    // 实现抛出受检异常的方法
    public static void throwCheckedException() throws CustomCheckedException {
        // 在此方法中抛出受检异常
        throw new CustomCheckedException("这是一个受检异常");
    }
}
```



Error继承自Throwable而不是继承自Exception，就是为了将error和exception分开处理，方便程序直接使用 "catch (Exception)"来捕捉异常而不必catch(error)。JDK中Error类的的注释（如下）也里提到过，Error是一种严重的问题，应用程序不应该捕捉它,因此我们在进行try catch的时候只对Exception及其子类进行捕捉就够了。



 		

​	

 	  			

 		

 	 